max_steps: 10000
check_val_every_n_epoch: 20
early_stop_patience: 5
early_stop_min_delta: 0.01
gradient_clip_val: 1.0
optimizer:
  _target_: AdamW
  lr: 1.0e-3
  weight_decay: 0.0
  betas: [0.9, 0.999]
scheduler:
  type: CosineAnnealingLR
  T_max: 10000
  eta_min: 1e-7
loss_type: psnr
